package com.acoustic.encoder.domain.music;

public enum MusicalCommand {

    PLAY_NOTE, SILENCE, MULTIPLY_VOLUME, CHANGE_INSTRUMENT,
    OFFSET_INSTRUMENT, OFFSET_OCTAVE, PLAY_PREVIOUS, NULL_COMMAND,
    DELAY_BEATS, OFFSET_LOCAL_BPM

}
