CONVERTER_BUTTON_TEXT = "Convert to Sound!"

SAVE_TEXT_BUTTON_TEXT = "Save Text"

LOAD_TEXT_BUTTON_TEXT = "Load Text"

INSTRUCTION_LABEL_TEXT = "Write the text you want to convert to sound:"
INSTRUCTION_LABEL_TGAP = 10
INSTRUCTION_LABEL_LGAP = 10
INSTRUCTION_LABEL_BGAP = 0
INSTRUCTION_LABEL_RGAP = 10

MAIN_SCROLL_TEXTAREA_TGAP = 0
MAIN_SCROLL_TEXTAREA_LGAP = 10
MAIN_SCROLL_TEXTAREA_BGAP = 0
MAIN_SCROLL_TEXTAREA_RGAP = 10

VOLUME_SLIDER_DIRECTION = 0
VOLUME_SLIDER_MIN = 0
VOLUME_SLIDER_MAX = 127
VOLUME_SLIDER_VALUE = 64
VOLUME_SLIDER_TICK_SPACING = 32
VOLUME_SLIDER_SHOW_LABELS = true

OCTAVE_SLIDER_DIRECTION = 0
OCTAVE_SLIDER_MIN = 1
OCTAVE_SLIDER_MAX = 10
OCTAVE_SLIDER_VALUE = 5
OCTAVE_SLIDER_TICK_SPACING = 2
OCTAVE_SLIDER_SHOW_LABELS = true

INSTRUMENT_SLIDER_DIRECTION = 0
INSTRUMENT_SLIDER_MIN = 0
INSTRUMENT_SLIDER_MAX = 127
INSTRUMENT_SLIDER_VALUE = 0
INSTRUMENT_SLIDER_TICK_SPACING = 32
INSTRUMENT_SLIDER_SHOW_LABELS = true

BPM_SLIDER_DIRECTION = 0
BPM_SLIDER_MIN = 10
BPM_SLIDER_MAX = 1000
BPM_SLIDER_VALUE = 120
BPM_SLIDER_TICK_SPACING = 250
BPM_SLIDER_SHOW_LABELS = true