CONVERSION_BUTTON_TEXT = MAKE IT SOUND
CONVERSION_BUTTON_FONT_SIZE = 25
CONVERSION_BUTTON_FLATLAF_STYLE = foreground: #00c8e0; hoverBackground: #00c8e0; hoverForeground: #222222; hoverBorderColor: #008396;

OPTION_BUTTON_PREFERRED_SIZE = 145,37

SAVE_TEXT_BUTTON_TEXT = Save Text
SAVE_TEXT_BUTTON_FONT_SIZE = 18

LOAD_TEXT_BUTTON_TEXT = Load Text
LOAD_TEXT_BUTTON_FONT_SIZE = 18

SAVE_PROJECT_BUTTON_TEXT = Save Project
SAVE_PROJECT_BUTTON_FONT_SIZE = 18

OPEN_PROJECT_BUTTON_TEXT = Open Project
OPEN_PROJECT_BUTTON_FONT_SIZE = 18

INSTRUCTION_LABEL_TEXT = Text 2 Sound:
INSTRUCTION_LABEL_FONT_SIZE = 20
INSTRUCTION_LABEL_TGAP = 10
INSTRUCTION_LABEL_LGAP = 10
INSTRUCTION_LABEL_BGAP = 0
INSTRUCTION_LABEL_RGAP = 0

MAIN_SCROLL_TEXTAREA_FONT_SIZE = 17
MAIN_SCROLL_TEXTAREA_ARC = 12
MAIN_SCROLL_TEXTAREA_TGAP = 0
MAIN_SCROLL_TEXTAREA_LGAP = 25
MAIN_SCROLL_TEXTAREA_BGAP = 0
MAIN_SCROLL_TEXTAREA_RGAP = 25

VOICE_SELECTOR_LABEL_TEXT = VOICE SETTINGS
VOICE_SELECTOR_LABEL_FONT_SIZE = 18
VOICE_SELECTOR_FONT_SIZE = 15
VOICE_SELECTOR_STARTING_OPTION = Voice 0
VOICE_SELECTOR_OPTION_0 = Voice 0
VOICE_SELECTOR_OPTION_1 = Voice 1
VOICE_SELECTOR_OPTION_2 = Voice 2
VOICE_SELECTOR_OPTION_3 = Voice 3

PARAMETER_LABEL_FONT_SIZE = 18
PARAMETER_PANEL_PREFERRED_SIZE = 250, 55
PARAMETER_PANEL_MAX_SIZE = 300, 55

VOLUME_SLIDER_DIRECTION = 0
VOLUME_SLIDER_MIN = 0
VOLUME_SLIDER_MIN_TO_SHOW = 0
VOLUME_SLIDER_MAX = 128
VOLUME_SLIDER_MAX_TO_SHOW = 127
VOLUME_SLIDER_TICK_SPACING = 32
VOLUME_LABEL_TEXT = Volume: 

OCTAVE_SLIDER_DIRECTION = 0
OCTAVE_SLIDER_MIN = 0
OCTAVE_SLIDER_MIN_TO_SHOW = 0
OCTAVE_SLIDER_MAX = 9
OCTAVE_SLIDER_MAX_TO_SHOW = 9
OCTAVE_SLIDER_TICK_SPACING = 3
OCTAVE_LABEL_TEXT = Octave: 

BPM_SLIDER_DIRECTION = 0
BPM_SLIDER_MIN = 0
BPM_SLIDER_MIN_TO_SHOW = 10
BPM_SLIDER_MAX = 1000
BPM_SLIDER_MAX_TO_SHOW = 1000
BPM_SLIDER_TICK_SPACING = 250
BPM_LABEL_TEXT = UNIVERSAL BPM: 

INSTRUMENT_LABEL_TEXT = Instrument:
INSTRUMENT_COMBOBOX_FONT_SIZE = 15
INSTRUMENT_COMBOBOX_INITIAL_INDEX = 0
INSTRUMENT_COMBOBOX_IS_EDITABLE = true