UNIVERSAL_BPM = 100

MAX_VOICE_INDEX = 3

VOICE_0_VOLUME = 100
VOICE_0_INSTRUMENT = 6
VOICE_0_OCTAVE = 6

VOICE_1_VOLUME = 80
VOICE_1_INSTRUMENT = 20
VOICE_1_OCTAVE = 5

VOICE_2_VOLUME = 60
VOICE_2_INSTRUMENT = 0
VOICE_2_OCTAVE = 4

VOICE_3_VOLUME = 40
VOICE_3_INSTRUMENT = 70
VOICE_3_OCTAVE = 3
