UNIVERSAL_BPM: 100

MAX_TRACK_INDEX = 3

TRACK_0_VOLUME: 50
TRACK_0_INSTRUMENT: 0
TRACK_0_OCTAVE: 5

TRACK_1_VOLUME: 60
TRACK_1_INSTRUMENT: 25
TRACK_1_OCTAVE: 2

TRACK_2_VOLUME: 70
TRACK_2_INSTRUMENT: 3
TRACK_2_OCTAVE: 1

TRACK_3_VOLUME: 80
TRACK_3_INSTRUMENT: 5
TRACK_3_OCTAVE: 9