A=PLAY_NOTE:9
B=PLAY_NOTE:11
C=PLAY_NOTE:0
D=PLAY_NOTE:2
E=PLAY_NOTE:4
F=PLAY_NOTE:5
G=PLAY_NOTE:7
H=PLAY_NOTE:10
a=SILENCE
b=SILENCE
c=SILENCE
d=SILENCE
e=SILENCE
f=SILENCE
g=SILENCE
h=SILENCE
\ =MULTIPLY_VOLUME:2
\!=CHANGE_INSTRUMENT:24
O=CHANGE_INSTRUMENT:110
o=CHANGE_INSTRUMENT:110
I=CHANGE_INSTRUMENT:110
i=CHANGE_INSTRUMENT:110
U=CHANGE_INSTRUMENT:110
u=CHANGE_INSTRUMENT:110
0=NULL_COMMAND
2=INCREMENT_INSTRUMENT:2
4=INCREMENT_INSTRUMENT:4
6=INCREMENT_INSTRUMENT:6
8=INCREMENT_INSTRUMENT:8
?=INCREMENT_OCTAVE:1
.=INCREMENT_OCTAVE:1
\n=CHANGE_INSTRUMENT:123
;=CHANGE_INSTRUMENT:15
1=CHANGE_INSTRUMENT:15
3=CHANGE_INSTRUMENT:15
5=CHANGE_INSTRUMENT:15
7=CHANGE_INSTRUMENT:15
9=CHANGE_INSTRUMENT:15
,=CHANGE_INSTRUMENT:114
default=PLAY_PREVIOUS
