PLAY_BUTTON_TEXT = Play
PAUSE_BUTTON_TEXT = Pause
REWIND_BUTTON_TEXT = Rewind
FORWARD_BUTTON_TEXT = Forward
SAVE_BUTTON_TEXT = Save

PLAY_BUTTON_ICON_PATH = /ui/icons/play_filled_32.png
PAUSE_BUTTON_ICON_PATH = /ui/icons/pause_filled_32.png
REWIND_BUTTON_ICON_PATH = /ui/icons/fast_rewind_B3B3B3.png
FORWARD_BUTTON_ICON_PATH = /ui/icons/fast_forward_B3B3B3.png
SAVE_BUTTON_ICON_PATH = /ui/icons/download_24_B3B3B3.png

NULL_TEXT_BUTTON_FONT_SIZE = 0
PROGRESS_TIME_LABEL_FONT_SIZE = 15

PLAY_PAUSE_BUTTON_PREFERRED_SIZE = 50, 50
SKIP_BUTTONS_PREFERRED_SIZE = 40, 40
SAVE_BUTTON_PREFERRED_SIZE = 24, 24

SEEKBAR_DIRECTION = 0
SEEKBAR_MIN = 0
SEEKBAR_MAX = 1000000
SEEKBAR_START_VALUE = 10
SEEKBAR_TICK_SPACING = 1000000