TITLE_LABEL_TEXT = Acoustic Encoder
TITLE_LABEL_FONT = Playfair Display Regular
TITLE_LABEL_FONT_SIZE = 60

OPEN_PROJECT_BUTTON_TEXT = Open Project
OPEN_PROJECT_BUTTON_FONT_SIZE = 23

NEW_PROJECT_BUTTON_TEXT = New Project
NEW_PROJECT_BUTTON_FONT_SIZE = 23