Button.arc = 16
Button.focusWidth = 2
Button.borderWidth = 2
Button.margin = {scaledInsets}5,8,5,8
Button.minimumWidth = 0
#Button.font = "Playfair Display Regular"

#[win]defaultFont = +2
#defaultFont = "Playfair Display Regular"
defaultFont = "Merriweather Light"
#h1.font = +12 $semibold.font
#large.font = +2