*.background = #000000

@compBackground = #222222
@compContrast = #aaaaaa

Button.background = @compBackground

ComboBox.background = @compBackground

RadioButton.icon.background = @compBackground
RadioButton.icon.borderColor = @compContrast
RadioButton.icon.selectedBackground = @compContrast
RadioButton.icon.checkmarkColor = @compBackground
RadioButton.icon.focusedBorderColor = @compBackground
RadioButton.icon.disabledBackground = @compBackground

TextArea.background = #454545
TextArea.foreground = @compContrast
TextArea.caretForeground = @compContrast