*.background = #010101

@compBackground = #222222
@compContrast = #aaaaaa
@redFeatures = #ff0000
@redBorder = #660000

Button.background = @compBackground
Button.rollover = true
Button.focus = false
Button.hoverBackground = @compContrast
Button.hoverForeground = @compBackground
Button.hoverBorderColor = @compContrast
Button.pressedBackground = @compContrast
Button.pressedBorderColor = @compContrast

ComboBox.background = @compBackground
ComboBox.foreground = @compContrast
ComboBox.caretForeground = @compContrast
ComboBox.rollover = true

Slider.thumbColor = @redFeatures
Slider.focusedColor = @redBorder

TextArea.background = #454545
TextArea.foreground = @compContrast
TextArea.caretForeground = @compContrast